config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :crms
  
  root 'crms#index'

end

app/models/crm.rb
class Crm < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
before_action :authentication!
end

app/controllers/crms_controller.rb
class CrmsController < ApplicationController
  before_action :set_crm, only: [:show, :edit, :update, :destroy]

  # GET /crms
  # GET /crms.json
  def index
    @crms = Crm.all
  end

  # GET /crms/1
  # GET /crms/1.json
  def show
  end

  # GET /crms/new
  def new
    @crm = Crm.new
  end

  # GET /crms/1/edit
  def edit
  end

  # POST /crms
  # POST /crms.json
  def create
    @crm = Crm.new(crm_params)

    respond_to do |format|
      if @crm.save
        format.html { redirect_to @crm, notice: 'Crm was successfully created.' }
        format.json { render :show, status: :created, location: @crm }
      else
        format.html { render :new }
        format.json { render json: @crm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crms/1
  # PATCH/PUT /crms/1.json
  def update
    respond_to do |format|
      if @crm.update(crm_params)
        format.html { redirect_to @crm, notice: 'Crm was successfully updated.' }
        format.json { render :show, status: :ok, location: @crm }
      else
        format.html { render :edit }
        format.json { render json: @crm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crms/1
  # DELETE /crms/1.json
  def destroy
    @crm.destroy
    respond_to do |format|
      format.html { redirect_to crms_url, notice: 'Crm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crm
      @crm = Crm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crm_params
      params.require(:crm).permit(:clientName, :phoneNumber, :contactPhoneNumber, :nip, :notes, :services)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/views/crms/_form.html.erb
<%= form_for(@crm) do |f| %>
  <% if @crm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crm.errors.count, "error") %> prohibited this crm from being saved:</h2>

      <ul>
      <% @crm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :clientName %><br>
    <%= f.text_area :clientName %>
  </div>
  <div class="field">
    <%= f.label :phoneNumber %><br>
    <%= f.text_field :phoneNumber %>
  </div>
  <div class="field">
    <%= f.label :contactPhoneNumber %><br>
    <%= f.text_field :contactPhoneNumber %>
  </div>
  <div class="field">
    <%= f.label :nip %><br>
    <%= f.text_field :nip %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :services %><br>
    <%= f.text_area :services %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crms/edit.html.erb
<h1>Editing crm</h1>

<%= render 'form' %>

<%= link_to 'Show', @crm %> |
<%= link_to 'Back', crms_path %>

app/views/crms/index.html.erb
<h1>Listing crms</h1>

<table>
  <thead>
    <tr>
      <th>Clientname</th>
      <th>Phonenumber</th>
      <th>Contactphonenumber</th>
      <th>Nip</th>
      <th>Notes</th>
      <th>Services</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crms.each do |crm| %>
      <tr>
        <td><%= crm.clientName %></td>
        <td><%= crm.phoneNumber %></td>
        <td><%= crm.contactPhoneNumber %></td>
        <td><%= crm.nip %></td>
        <td><%= crm.notes %></td>
        <td><%= crm.services %></td>
        <td><%= link_to 'Show', crm %></td>
        <td><%= link_to 'Edit', edit_crm_path(crm) %></td>
        <td><%= link_to 'Destroy', crm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crm', new_crm_path %>

app/views/crms/new.html.erb
<h1>New crm</h1>

<%= render 'form' %>

<%= link_to 'Back', crms_path %>

app/views/crms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clientname:</strong>
  <%= @crm.clientName %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @crm.phoneNumber %>
</p>

<p>
  <strong>Contactphonenumber:</strong>
  <%= @crm.contactPhoneNumber %>
</p>

<p>
  <strong>Nip:</strong>
  <%= @crm.nip %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @crm.notes %>
</p>

<p>
  <strong>Services:</strong>
  <%= @crm.services %>
</p>

<%= link_to 'Edit', edit_crm_path(@crm) %> |
<%= link_to 'Back', crms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Workspace" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Workspace</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>